name: Go Build and Release

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24'
    - name: Build
      run: go build -o spammer.exe -v .
    - name: Test
      run: go test -v .
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: spammer-app
        path: spammer.exe

  release:
    needs: build
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
    - name: Download Artifact
      uses: actions/download-artifact@v4
      with:
        name: spammer-app
        path: .  # Downloads into the current directory
    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: v1.0.${{ github.run_number }}
        files: ./spammer.exe
